### ISSUE TITLE
Setting up plugin with jest

### ISSUE THREAD

**Issue by TonyHYK** [giuseppeg/styled-jsx-plugin-sass#12]
Hi, I got some tests running with next and jest using the following .babelrc config.
https://github.com/zeit/next.js/blob/master/examples/with-jest/.babelrc

I ran into some problems when jest encountered sass-specific syntax. I tried fiddling with .babelrc to get the plugin running on test env but couldn't get it working. I think I'm just bad at configuring babel, could I get some help setting this up? Thanks!

**Comment by Tomekmularczyk** [comment]
Don't you need to set plugins like so: 

```javascript
  "plugins": [
    ["styled-jsx/babel", { "plugins": ["styled-jsx-plugin-sass"] }],
  ],
```

?

**Comment by Tomekmularczyk** [comment]
Could you show your .babelrc config?

**Comment by TonyHYK** [comment]
Hi, I was able to figure it out, and my babelrc for the test env is the following for future references:
```
    "test": {
      "presets": [ [
          "next/babel", {
            "preset-env": { "modules": "commonjs" },
            "styled-jsx": {
              "plugins": [
                ["styled-jsx-plugin-sass", {"sassOptions": {"includePaths": ["./client/styles"]}}]
              ]
            }
          }
        ]]
    }
```

Thanks!

**Comment by Tomekmularczyk** [comment]
I don’t use nextjs but in my case it helped to just remove ‘styled-jsx/babel‘ plugin in ‘test’ env.

**Comment by giuseppeg** [comment]
for jest we recommend to remove styled-jsx as @Tomekmularczyk suggested see https://github.com/zeit/styled-jsx#rendering-in-tests
