### ISSUE TITLE
Issue with Sass without ; and {

### ISSUE THREAD

**Issue by afzal273** [giuseppeg/styled-jsx-plugin-sass#20]
Hello, I'm unable to write sass format omitting `;` and `{}`; getting the following error in jsx files

`Module build failed: Error: Invalid CSS after " ": expected 1 selector or at-rule, was "{"`

Here's my babelrc
```{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "optimizeForSpeed": false,
          "plugins": [
            [
              "styled-jsx-plugin-sass", {
              "sassOptions": {
                "includePaths": [ "./components/styles/", "./pages/styles/" ],
                "precision": 8,
              }
            }],
            "styled-jsx-plugin-postcss"
          ]
        }
      }
    ]
  ]
}```

Am I missing something?

**Comment by giuseppeg** [comment]
can you show me an example of css?

**Comment by afzal273** [comment]
Here's an example
Not working
```import css from 'styled-jsx/css';

export default css`
  @import "variables"
  
  .rdc-btn
    font-weight: 500
    padding: 0.75em 1.5em
    display: inline-block
    border-radius: $border-radius
    border: 1px solid $color-dark
    font-size: 1em
    cursor: pointer
    &:hover
      transition: 300ms linear
`;
```

Working
```import css from 'styled-jsx/css';

export default css`
  @import "variables"
  
  .rdc-btn {
    font-weight: 500;
    padding: 0.75em 1.5em;
    display: inline-block;
    border-radius: $border-radius;
    border: 1px solid $color-dark;
    font-size: 1em;
    cursor: pointer;
    &:hover {
      transition: 300ms linear;
      }
   }
`;
```

**Comment by giuseppeg** [comment]
have you tried to remove `styled-jsx-plugin-postcss`? Also can you share a minimal testcase (a next.js app with your setup and just a single component with sass styles)?

**Comment by afzal273** [comment]
Yes I tried to remove `styled-jsx-plugin-postcss` and it doesn't work, perhaps it needs sass to be in scss format? Here's a test case repo - https://github.com/afzal273/testing-styled-jsx-comp-library. Thanks so much for your help.

**Comment by giuseppeg** [comment]
alright first of all if you want to use the indent based syntax you need to set `indentedSyntax` to `true` in the  `sassOptions`. Once you have that you need to remove the indentation :) right now in `buttons-not-working` the css is indented an it will break if you don't remove that because with that type of syntax indentation is important. Hope this helps

**Comment by giuseppeg** [comment]
alright first of all if you want to use the indent based syntax you need to set `indentedSyntax` to `true` in the  `sassOptions`. Once you have that you need to remove the indentation :) right now in `buttons-not-working` the css is indented an it will break if you don't remove that because with that type of syntax indentation is important. Hope this helps

**Comment by afzal273** [comment]
Awesome, it works now. Thanks so much!!

**Comment by itamud** [comment]
Same issue here, set `indentedSyntax` to `true` didn't help me out...
Here's my `.babelrc.js` and  `css`, with these code, it throws the same error message:

`Module build failed: Error: Invalid CSS after " ": expected 1 selector or at-rule, was "{"`

```js
module.exports = {
  "env": {
    "development": {
      "presets": ["next/babel"]
    },
    "production": {
      "presets": ["next/babel"]
    },
    "test": {
      "presets": [["next/babel", { "preset-env": { "modules": "commonjs" } }]]
    }
  },
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "optimizeForSpeed": true,
          "plugins": [
            [
              "styled-jsx-plugin-sass", {
              "sassOptions": {
                "indentedSyntax": true 
              }
            }],
          ]
        }
      }
    ],
  ],
  "plugins": [
    [
      "styled-jsx/babel",
      {
        "plugins": [
          [
            "styled-jsx-plugin-sass",
            {
              "sassOptions": {
                "indentedSyntax": true
              }
            }
          ]
        ]
      }
    ]
  ]
}
```

```js
import React from 'react'
import { Layout } from '../components'

export default function Index () {
  return (
    <Layout>
      <p>home</p>
      <style jsx>{`
        p
          color: red
      `}
      </style>
    </Layout>
  )
}
```

When I delete the `plugins` section in the  `.babelrc.js`, there're no errors any more, but the style, which renders the color of element `p` to red, doesn't apply...

Anything wrong with my code?

**Comment by vanGalilea** [comment]
Indented syntax still not working for me, tried all of the above...

does somebody have an idea how to solve this issue ?

tnx
