### ISSUE TITLE
Unable to import sass files when using in component library

### ISSUE THREAD

**Issue by afzal273** [giuseppeg/styled-jsx-plugin-sass#21]
Hello,

I'm creating a component library which is using styled-jsx and styled-jsx-plugin-sass. When I use this library as a dependency in another next project I'm getting this error

`Module build failed: Error:  File to import not found or unreadable: _variables.sass.`

It works fine within the component library, 

The css file in component library looks like so -

variables is a file `_variables.scss` in the same folder.

```
@import "variables"; 

.inner-heading {
  color: green;
  font-size: 2em;
}

.heading {
  font-size: 2em;
  color: $brand-primary;
}
```

But when it comes to the project importing the component library I get the error above. I'm making sure to include the path in sassoptions. 

```
"sassOptions": {
                "includePaths": [ "./src/app/styles/", "./node_modules/bootstrap-sass/assets/stylesheets/", "./node_modules/test-react-styled-jsx-components/dist/styles/" ],
                "precision": 8,
              }
```

If I import the sass file from the library into a css file in my project, it works fine, but somehow it is not working when it's used from the component library (from either a component or even if the css file is tried to be imported)

**Comment by giuseppeg** [comment]
Can you make a minimal testcase (repo) and share it with me?

**Comment by afzal273** [comment]
Thanks so much for helping @giuseppeg , here's a test case repo - https://github.com/afzal273/test-next-project ; it is using a comps library - https://github.com/afzal273/testing-styled-jsx-comp-library which I published to test.

**Comment by giuseppeg** [comment]
alright first of all if you want to use the indent based syntax you need to set `indentedSyntax` to `true` in the  `sassOptions`. Once you have that you need to remove the indentation :) right now in `buttons-not-working` the css is indented an it will break if you don't remove that because with that type of syntax indentation is important. Hope this helps

**Comment by giuseppeg** [comment]
> But when it comes to the project importing the component library I get the error above

you need to transpile your components like you would do with any other JS library so that your project can use the compiled version. You can take this issue https://github.com/zeit/styled-jsx/issues/159 and the instructions in it as an example

**Comment by afzal273** [comment]
Thanks for the tip @giuseppeg, perhaps I'm not transpiling correctly or missing a config , now I'm getting the error below. Could you please let me know what I'm missing as I don't use rollup as in the example in https://github.com/zeit/styled-jsx/issues/159.

I've updated code in the two repos to add the prod build step using instructions from - https://medium.com/@efreyreg/create-react-component-libraries-with-storybook-and-styled-jsx-8999f423f06b (https://github.com/afzal273/test-next-project ; it is using a comps library - https://github.com/afzal273/testing-styled-jsx-comp-library)

Thanks so much for your help, much appreciated.

```
Error: styled-jsx/css: if you are getting this error it means that your `css` tagged template literals were not transpiled.
    at module.exports (//testing/test-next-project/node_modules/styled-jsx/css.js:2:9)
    at Object.<anonymous> (//testing/test-next-project/node_modules/test-styled-jsx-comps-library/dist/styles/buttons-working.js:17:37)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (//testing/test-next-project/node_modules/test-styled-jsx-comps-library/dist/RdcButton.js:13:23)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
```
