### ISSUE TITLE
Feature Request: Add support for dart-sass

### ISSUE THREAD

**Issue by depadiernos** [giuseppeg/styled-jsx-plugin-sass#24]
As a pure javascript alternative, [dart-sass](https://www.npmjs.com/package/dart-sass) makes it so there is no dependency to platform specific binaries.

**Comment by giuseppeg** [comment]
If the api is similar to node-sass you can install `dart-sass` and alias it to `node-sass`

**Comment by depadiernos** [comment]
I think the API is meant to be as close to node-sass as possible. I’ll give it a try. 👍

**Comment by oskari** [comment]
Dart-sass is now the primary implementation of sass, maybe this should support it and alias to node-sass if somebody wants to use that still.
