### ISSUE TITLE
Duplicate and probably unnecessary paths in includePath

### ISSUE THREAD

**Issue by giuseppeg** [giuseppeg/styled-jsx-plugin-sass#27]
We noticed that the plugin adds duplicate paths to the `includePath` array while processing files https://github.com/giuseppeg/styled-jsx-plugin-sass/blob/master/index.js#L17

Looking at the source code it seems that we also add every possible path to the array. I suggest to remove these and only add base paths (i.e. common parent paths). Quoting @atombender :

>  this might be a breaking change, if people have accidentally used relative imports. For example, @import "foo" will find ./src/foo.scss or whatever today, but not if we fix the path modification.

I haven't used sass in a while so I don't remember how path resolution works but `@import "foo"` seems wrong to me / misusage. Is that common? Also would it still work if we only have `./src` in the `includePath`? I was suggesting to only add a new path if there is no parent folder already. eg.

```
./src/
./bar/
```

but not `./src/bar/`. So `@import "foo"` will find `./src/foo.scss` but probably not `./src/bar/foo.scss` or anything in other folders. Does people add a gazillion folders in the `includePath` array? I think explicit relative imports should be preferable to magic path resolution. In case we can make a major release.

**Comment by atombender** [comment]
I think the best and least magical solution is to not change the paths at all, and just rely on the default behaviour. After all, you can pass your own `includePaths`. Explicit is usually better than implicit, especially in this case when there's no way to subtract stuff from the list.

**Comment by giuseppeg** [comment]
Agreed! Let's do that and do a major release

**Comment by giuseppeg** [comment]
@atombender just published `1.0.0` which includes your patch. Thank you again for the contribution!

**Comment by atombender** [comment]
Awesome, thanks!
