### ISSUE TITLE
Error in fragment

### ISSUE THREAD

**Issue by Soundvessel** [giuseppeg/styled-jsx-plugin-sass#29]
**Do you want to request a feature or report a bug?**

Bug.

**What is the current behavior?**

Styled JSX inside a React Fragment container causes a rendering error.

>Warning: Received `true` for a non-boolean attribute `jsx`.

Use of this babel config has appeared to cause a resolved issue with styled-jsx (https://github.com/zeit/styled-jsx/issues/458) to resurface.

**What is the expected behavior?**

No rendering error.

**Steps to produce**

Same as https://github.com/zeit/styled-jsx/issues/458 but the the following babel config to provide SASS support in JSX.

`.babelrc`
```{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "plugins": [
            ["styled-jsx-plugin-sass", {
              "sassOptions": {
                "includePaths": ["./styles", "./node_modules"]
              }
            }
            ]
          ]
        }
      }
    ]
  ]
}
```

**Comment by Soundvessel** [comment]
Note the current workaround is to use the old `<React.Fragment></React.Fragment>` syntax.

**Comment by giuseppeg** [comment]
Yeah styled-jsx is not fully Babel 7 compatible yet
