### ISSUE TITLE
media query expression must begin with '('

### ISSUE THREAD

**Issue by Tomekmularczyk** [giuseppeg/styled-jsx-plugin-sass#4]
I don't like to bring issues but I came across a strange error...

```
import React from 'react';
import logo from 'static/react-logo.svg';

const breakpoints = Object.freeze({
  bsSM: '(min-width: 768px)',
});

const IndexPage = () => (
  <div className="IndexPage">
    <div className="header">
      <img src={logo} className="logo" alt="logo" />
      <h2>Yeah, React!</h2>
    </div>
    <style jsx>{`
      .IndexPage {
        text-align: center;

        @media screen and ${breakpoints.bsSM} {
          background-color: red;
        }
      }
    `}</style>
  </div>
);

export default IndexPage;

```

the `breakpoints` placeholder causes the error `media query expression must begin with '('
`

I've read it has something to do with `@import ` and lacking semicolon. But it doesn't make sense here.

[repo](https://github.com/Tomekmularczyk/react-starter/blob/media-query-expression-error/src/app/pages/index.jsx)

**Comment by giuseppeg** [comment]
Yep we need a better regular expression for that https://github.com/giuseppeg/styled-jsx-plugin-sass/blob/master/index.js#L4-L10 Can you give it a try?

**Comment by Tomekmularczyk** [comment]
@giuseppeg [#6](https://github.com/giuseppeg/styled-jsx-plugin-sass/pull/6)
