### ISSUE TITLE
Plugins is not a function

### ISSUE THREAD

**Issue by justintemps** [giuseppeg/styled-jsx-plugin-sass#44]
Loading styled-jsx-plugin-sass with the below .babelrc throws this error from the first loaded component with <style jsx>. This is with Next 10.01.

```
TypeError: /abs/path/to/Component.tsx: plugins is not a function
```

.babelrc
```
{
  "presets": ["next/babel"],
  "plugins": [
    [
      "styled-jsx/babel", { "plugins": ["styled-jsx-plugin-sass"] }
    ]
  ]
}

```

**Comment by empty916** [comment]
i have same problem

**Comment by empty916** [comment]
@justintemps i knew it why, document say you need use node-sass instead of sass
